api/urls.py
from django.urls import path

from .views import (EarningSchemeApiView, ExpensesApiView, JobApiView,
                    NetworkApiView, NeuronetApiView, OtherSource, UsersApiView)

app_name = 'api'

urlpatterns = [
    path('users', UsersApiView.as_view(), name='api_users'),
    path('neuronet', NeuronetApiView.as_view(), name='api_neuronet'),
    path('epxenses', ExpensesApiView.as_view(), name='epxenses'),
    path(
        'earning_scheme', EarningSchemeApiView.as_view(),
        name='earning_scheme',
        ),
    path('job_payment', JobApiView.as_view(), name='job'),
    path('network_payment', NetworkApiView.as_view(), name='network_payment'),
    path('other_payment', OtherSource.as_view(), name='other_payment')
]

job/urls.py
from django.urls import path

from job import views

app_name = 'job'

urlpatterns = [
    path('', views.job_view, name='job_view'),
    path('neuronet/', views.neiro_view, name='neiro_view'),
    path('scheme/', views.earning_scheme, name='scheme_view'),
    path('finance/', views.finance_view, name='finance_view'),
    path('finance/add_work/', views.finance_add_work, name='finance_add_view'),
    path(
        'finance/add_other_work/', views.finance_other_add,
        name='finance_other_add_view'
        ),
    path(
        'finance/list/', views.finance_list,
        name='finance_list_view'
        ),
    path(
        'finance/special/', views.special,
        name='special_view',
    ),
    path('crypto/', views.CryptoListView.as_view(), name='crypto'),
    path('finance/calculation/', views.finance_calculation_view,
         name='finance_calculation'),
    path(
        'finance/list/expenses', views.finance_list_expenses,
        name='finance_list_expenses_view'
        ),
    path(
        'worker/edit/', views.ProfileUpdateView.as_view(),
        name='profile_edit'
        ),
]

max_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('job/', include('job.urls', namespace='job')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

job/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView
from PIL import Image

from users.models import Special, Worker

from .crypto.api import return_api
from .forms import (Earning_schemeForm, Expenses_model_form, Job_Reg_Form,
                    JobForm, Maling_model_form, NetworkForm, NeuralNetworkForm,
                    Other_Source_Form, Other_Source_Reg_Form,
                    ProfileUpdateForm, SpecialForm, Сontacts_model_form)
from .models import (Crypto_model, Earning_scheme, Expenses_model, Job,
                     Job_Payment, Network_Payment, Neural_network,
                     Other_Source, Other_Source_model)

USERS_FOR_USIBILLITY = 100


def categogy_count():
    """Подсчет категории"""
    count_networks = Neural_network.objects.count()
    count_worker = Worker.objects.count() + USERS_FOR_USIBILLITY
    count_scheme = Earning_scheme.objects.count()
    count_job = Job.objects.count()
    other_source_model = Other_Source_model.objects.count()
    forms = [
        count_networks, count_worker, count_scheme,
        count_job, other_source_model,
    ]
    return forms


def job_view(request):
    if request.method == 'POST':
        form_contacts = Сontacts_model_form(request.POST, request.FILES)
        form_maling = Maling_model_form(request.POST, request.FILES)
        if form_maling.is_valid():
            form_maling = form_maling.save()
            return redirect(request.META.get('HTTP_REFERER'))
        if form_contacts.is_valid():
            form_contacts = form_contacts.save()
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        form_contacts = Сontacts_model_form()
        form_maling = Maling_model_form()
    count_networks = Neural_network.objects.count()
    #  Добавим видимость посещаемости сайта
    count_worker = Worker.objects.count() + USERS_FOR_USIBILLITY
    context = {
        'form_maling': form_maling,
        'form_contacts': form_contacts,
        'count_networks': count_networks,
        'count_worker': count_worker,
    }
    return render(request, 'main/index.html', context)


def neiro_view(request):
    networks = Neural_network.objects.all()
    if request.method == 'POST':
        form = NeuralNetworkForm(request.POST, request.FILES)
        if form.is_valid():
            # Сначала получаем экземпляр без сохранения в БД
            instance = form.save(commit=False)
            if instance.image:  # Проверяем, загружено ли изображение
                img = Image.open(instance.image)
                img.thumbnail((300, 200))  # Изменяем размер до 300x300
                img.save(instance.image.path)  # Перезаписываем изображение
            instance.save()
    else:
        form = NeuralNetworkForm()
    context = {
        'networks': networks,
        'form': form,
    }
    return render(request, 'main/press-single.html', context)


@login_required
def finance_view(request):
    stable_expenses = sum(Expenses_model.objects.filter(
        author_id=request.user.id, type_expenses='Постоянные расходы',).
                          values_list('price', flat=True)
    )
    variable_expenses = sum(Expenses_model.objects.filter(
        author_id=request.user.id, type_expenses='Переменные расходы',).
                            values_list('price', flat=True)
    )
    unexpected_expenses = sum(Expenses_model.objects.filter(
        author_id=request.user.id, type_expenses='Неожиданные расходы',).
                              values_list('price', flat=True)
    )
    planned_expenses = sum(Expenses_model.objects.filter(
        author_id=request.user.id,
        type_expenses='Планируемые заранее расходы',).
                           values_list('price', flat=True)
    )
    amount_expenses = sum([
        stable_expenses, variable_expenses,
        unexpected_expenses, planned_expenses,
        ]
    )
    monthly_income = Expenses_model.objects.filter(
        author_id=request.user.id,
        date__month=timezone.now().month,
        date__year=timezone.now().year
    ).values('type_expenses').annotate(
        total_price=Sum('price')).order_by('type_expenses')
    amount_expenses_month = sum(Expenses_model.objects.filter(
        author_id=request.user.id,
        date__month=timezone.now().month,
        date__year=timezone.now().year).values_list(
            'price', flat=True))
    date_now = timezone.now().strftime('%B')
    income_job = sum(Job_Payment.objects.filter(
        worker_id=request.user.id,
        date__month=timezone.now().month,
        date__year=timezone.now().year).values_list(
            'payment_in_money', flat=True)
        )
    income_other_source = sum(Other_Source.objects.filter(
        worker_id=request.user.id,
        date__month=timezone.now().month,
        date__year=timezone.now().year).values_list(
            'payment_in_money', flat=True))
    income_network = sum(Network_Payment.objects.filter(
        worker_id=request.user.id,
        date__month=timezone.now().month,
        date__year=timezone.now().year).values_list(
            'payment_in_money', flat=True)
        )
    income_sum_month = sum((income_network, income_other_source, income_job))
    forms = categogy_count()
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        form1 = NetworkForm(request.POST, request.FILES)
        form2 = Other_Source_Form(request.POST, request.FILES)
        if form.is_valid():
            job_payment = form.save(commit=False)
            job_payment.worker = request.user
            job_payment.save()
            return redirect(request.META.get('HTTP_REFERER'))
        if form1.is_valid():
            network_payment = form1.save(commit=False)
            network_payment.worker = request.user
            network_payment.save()
            return redirect(request.META.get('HTTP_REFERER'))
        if form2.is_valid():
            other_payment = form2.save(commit=False)
            other_payment.worker = request.user
            other_payment.save()
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        form = JobForm()
        form1 = NetworkForm()
        form2 = Other_Source_Form()
    user = Worker.objects.get(id=request.user.id)
    sum_other = sum(Other_Source.objects.filter(
        worker_id=request.user.id
        ).values_list('payment_in_money', flat=True))
    day_other = sum(Other_Source.objects.filter(
        worker_id=request.user.id
        ).values_list('duration', flat=True))
    sum_network = sum(Network_Payment.objects.filter(
        worker_id=request.user.id
        ).values_list('payment_in_money', flat=True))
    day_network = sum(Network_Payment.objects.filter(
        worker_id=request.user.id
        ).values_list('duration', flat=True))
    sum_job = sum(Job_Payment.objects.filter(
        worker_id=request.user.id
        ).values_list('payment_in_money', flat=True))
    day_job = sum(Job_Payment.objects.filter(
        worker_id=request.user.id
        ).values_list('duration', flat=True))
    day_amount = sum([day_other, day_network, day_job])
    total_amount = sum([sum_other, sum_network, sum_job])
    context = {
        'forms': forms,
        'day_amount': day_amount,
        'total_amount': total_amount,
        'sum_job': sum_job,
        'sum_network': sum_network,
        'sum_other': sum_other,
        'user': user,
        'form': form,
        'form1': form1,
        'form2': form2,
        'stable_expenses': stable_expenses,
        'variable_expenses': variable_expenses,
        'unexpected_expenses': unexpected_expenses,
        'planned_expenses': planned_expenses,
        'amount_expenses': amount_expenses,
        'monthly_income': monthly_income,
        'amount_expenses_month': amount_expenses_month,
        'date_now': date_now,
        'income_job': income_job,
        'income_other_source': income_other_source,
        'income_network': income_network,
        'income_sum_month': income_sum_month,
    }
    return render(request, 'main/single.html', context)


@login_required
def finance_add_work(request):
    """Добавление работы"""
    if request.method == 'POST':
        form3 = Job_Reg_Form(request.POST, request.FILES)
        form4 = Other_Source_Reg_Form(request.POST, request.FILES)
        if form3.is_valid():
            form3.save()
            return redirect('/job/finance/')
        if form4.is_valid():
            form4.save()
            return redirect('/job/finance/')
    else:
        form3 = Job_Reg_Form()
        form4 = Other_Source_Reg_Form()
    context = {
        'form3': form3,
        'form4': form4,
    }
    return render(request, 'main/single_add.html', context)


@login_required
def finance_other_add(request):
    """Добавление подработки"""
    if request.method == 'POST':
        form4 = Other_Source_Reg_Form(request.POST, request.FILES)
        if form4.is_valid():
            form4.save()
            return redirect('/job/finance/')
    else:
        form4 = Other_Source_Reg_Form()
    context = {
        'form4': form4,
    }
    return render(request, 'main/single_other_add.html', context)


@login_required
def finance_list(request):
    """Общая информация о финансах"""
    user = Worker.objects.get(id=request.user.id)
    sum_other = sum(Other_Source.objects.filter(
        worker_id=request.user.id
        ).values_list('payment_in_money', flat=True))
    sum_network = sum(Network_Payment.objects.filter(
        worker_id=request.user.id
        ).values_list('payment_in_money', flat=True))
    sum_job = sum(Job_Payment.objects.filter(
        worker_id=request.user.id

job/templates/main/crypto.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="site-section-cover overlay inner-page bg-light"
style="background-image: url('/static/images/hero_1.jpg')" data-aos="fade">
<div class="container">
  <div class="row align-items-center justify-content-center text-center">
    <div class="col-lg-10">
      <div class="box-shadow-content">
        <div class="block-heading-1">
          <span class="d-block mb-3 text-white" data-aos="fade-up">
            <h1 class="mb-4" data-aos="fade-up" data-aos-delay="100">Котировки в реальном времени
            </h1>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<section class="site-section">
<div class="container">
  <div class="row">
    <div class="col-md-8 blog-content">
      <p class="lead">В самом сердце цифрового царства, где биты танцевали на блокчейне, зародилась история криптовалют.</p>
      <p>В 2008 году, на фоне финансового кризиса, Сатоши Накамото, загадочный псевдоним, опубликовал новаторскую статью, в которой представил концепцию Биткойна. Это была децентрализованная цифровая валюта, которая не зависела ни от какого банка или правительства.</p>
      <blockquote>
        <p>Транзакции Биткойна записывались в неизменяемый регистр, известный как блокчейн, который распространялся по сети компьютеров по всему миру. Каждый компьютер, известный как узел, имел копию блокчейна, обеспечивая беспрецедентную безопасность и прозрачность.</p>
      </blockquote>
      <p>Поначалу Биткойн рассматривался как диковинка, но по мере того, как росла его популярность, стало ясно, что он обладает потенциалом революционизировать финансовую систему. К 2013 году его стоимость резко возросла, сделав его привлекательным вариантом инвестиций.</p>
      <p>Рост Биткойна породил волну подражателей, известных как альткоины. Ethereum, Litecoin и Ripple были одними из самых известных, каждый со своими уникальными функциями и приложениями.</p>
      <p>Криптовалюты быстро завоевали популярность, обещая конфиденциальность, безопасность и децентрализацию. Они открыли новые возможности для инвестиций, платежей и финансовой инклюзии.</p>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="table-btn-2 active-btn-2" data-target="crypto" type="button">Криптовалюты</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="table-btn-2" data-target="shares" type="button">Акции</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="table-btn-2" data-target="my_crypto" type="button">Крипта сайта</button>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="table show" id="crypto">
                <div class="table-responsive">
                  <ul class="list-group">
                    {% for coin in api_values %}
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                          <h2 class="h4 me-3"><a href="" class="text-dark">Символ: {{ coin.symbol }}</a></h2>
                          <span class="text-secondary">Цена: {{ coin.lastPrice }} долларов</span>
                        </div>
                        <div class="text-end">
                          {% if coin.priceChangePercent > '0' %}
                          <p class="mb-0 text-success">Изменение за 24 часа: {{ coin.priceChangePercent }}</p>
                          {% else %}
                          <p class="mb-0 text-danger">Изменение за 24 часа: {{ coin.priceChangePercent }}</p>
                          {% endif %}
                          <p class="mb-0">Объем за 24 часа: {{ coin.volume }}</p>
                        </div>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="table" id="shares">
                <div class="table-responsive2">
                  <ul class="list-group">
                    {% for coin in shares_values %}
                      <li class="list-group-item2 d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                          <h2 class="h4 me-3"><a href="" class="text-dark">Краткое наименование ценной бумаги: {{ coin.0 }}</a></h2>
                          <span class="mb-0 text-success">Цена закрытия предыдущей торговой сессии: {{ coin.1 }} рублей</span>
                          <span class="mb-0 text-danger">Средневзвешенная цена предыдущей торговой сессии: {{ coin.2 }} рублей</span>
                        </div>
                        <div class="text-end">
                          <p class="mb-0 text-truncate">Полное наименование ценной бумаги: {{ coin.3 }}</p>
                          <p class="mb-0">Размер лота: {{ coin.4 }}</p>
                          <p class="mb-0">Статус ценной бумаги: {{ coin.5 }}</p>
                        </div>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="table show" id="my_crypto">
                <div class="table-responsive">
                  <ul class="list-group">
                    {% for value in page_obj %}
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                          <h2 class="h4 me-3"><a href="" class="text-dark">Автор: {{ value.author }}</a></h2>
                          <span class="text-secondary">Название: {{ value.title }} долларов
                            <img src="{{ value.image.url }}" alt="Image" class="Midjourney" style="width: 150px; height: 125px;">
                          </span>
                        </div>
                        <div class="text-end">
                          <p class="mb-0">Url адрес: {{ value.url }}</p>
                          <p class="mb-0 text-success">Курс на момент добавления: {{ value.course }}</p>
                          <p class="mb-0">Описание криптовалют
      ы: {{ value.discription }}</p>
                          <p class="mb-0">Дата добавления: {{ value.date_joined }}</p>
                          <p class="mb-0">Последнее обновление : {{ value.last_updated }}</p>
                        </div>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>







    </div>
    <div class="col-md-4 sidebar">
      {% if user.is_authenticated %}
      <div class="sidebar-box">
        <img src='{{ user.image.url }}' alt="Image placeholder" class="img-fluid mb-4 w-75 rounded-circle">
        <div style="border: 1px solid black; padding: 10px;">
          <h3 class="text-black">Все о авторе {{ user.username }}</h3>
          {% if user.first_name %}
          <p>Имя: {{ user.first_name }}</p>
          {% endif%}
          {% if user.last_name %}
          <p>Фамилия: {{ user.last_name }}</p>
          {% endif%}
          {% if user.is_staff %}
          <p>Статус: Админ</p>
          {% else %}
          <p>Статус: Пользователь</p>
          {% endif %}

          <p>Почта: {{ user.email }}</p>
          <p>Дата регистрации: {{ user.date_joined }}</p>
        </div>
        <br>
        <h3 class="text-black">Описание профиля</h3>
        <p id="shortDescription">{{ user.description_for_profil|slice:":40" }} ...</p>
        <p id="fullDescription" style="display:none">{{ user.description_for_profil }}</p>
        <button style="border: 1px solid black; padding: 10px;" onclick="toggleDescription()">Читать
          далее</button>
      </div>
      {% endif %}


      
      <div class="site-section" id="press-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 mb-1 mb-lg-1">
            </div>
      <div class="sidebar-box">
        <h3 class="text-black">Наставление</h3>
        <p>Прежде, чем начать считать свои деньги, спроси себя, готов ли ты складывать двузначные числа$$</p>
      </div>
      <div class="sidebar-box">
        <div class="categories">
          <h3 class="text-black">Данные</h3>
          <li><a href="#">Кол-во нейросетей<span>{{forms.0}}</span></a></li>
          <li><a href="#">Кол-во пользователей<span>{{forms.1}}</span></a></li>
          <li><a href="#">Кол-во схем <span>{{forms.2}}</span></a></li>
          <li><a href="#">Кол-во работ <span>{{forms.3}}</span></a></li>
          <li><a href="#">Кол-во иных заработков<span>{{forms.4}}</span></a></li>
        </div>
      </div>
    </div>
  </div>
</div>
    </div>
</section>
<style>
@media (max-width: 767px) {
  .list-group-item {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .list-group-item img {
    width: 100px;
    height: 100px;
  }
  .list-group-item span {
    display: block;
  }
  .text-end {
    text-align: center;
  }
}
</style>
<style>
  .table-responsive2 .list-group-item2 p {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  </style>
  <script src='{% static "js/owl.carousel.min.js" %}'></script>
  <script src='{% static "js/jquery.magnific-popup.min.js" %}'></script>
  <script src='{% static "js/jquery.sticky.js" %}'></script>
  <script src='{% static "js/jquery.waypoints.min.js" %}'></script>
  <script src='{% static "js/jquery.animateNumber.min.js" %}'></script>
  <script src='{% static "js/aos.js" %}'></script>
  <script src='{% static "js/prof.js" %}'></script>
  <script src='{% static "js/chit.js" %}'></script>
{% endblock %}

job/templates/main/expenses_list.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="Midjourney">
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12" style="border: 1px solid black; padding: 10px;">
        <div class="row">
          <div class="col-md-6 order-md-2">
            <div class="Midjourney">
              <h4 style="color: #01070e;"> Данные о пользователе: {{user.username}} </h4>
              <h4 style="color: #01070e;">id: {{user.id}} </h4>
              <h4 style="color: #01070e;">Последний вход в систему: {{user.last_login}} </p>
              <h4 style="color: #01070e;">Имя: {{user.first_name}} </h4>
              <h4 style="color: #01070e;">Фамилия: {{user.last_name}} </p>
              <h4 style="color: #01070e;">Дата регистрации: {{user.date_joined}} </h4>
              <h4 style="color: #01070e;">Почта: {{user.email}} </h4>
              <h4 style="color: #01070e;">Роль: {{user.role}} </h4>
              <h5 style="color: #01070e;">Описание профиля: {{ user.description_for_profil }}</h5>
            </div>
          </div>
          <div class="col-md-6 order-md-1">
            <div class="text-center">
              <img src="{{ user.image.url }}" alt="Image placeholder" class="img-fluid mb-5 w-75 rounded-circle border border-dark d-block mx-auto" style="max-width: auto; height: auto;">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="Midjourney">
  <div class="container">
    <div class="row">
      <div class="col-md-10 mx-auto blog-content">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <!-- <style>
          #chart,
          #chart-days {
            width: 500px;
            height: 500px;
            display: table-cell; /* Устанавливаем блоки в одну линию */
          }
        </style>
        <div id="chart"></div>
        <div id="chart-days"></div> -->
        <!-- <script>
          // JavaScript код для создания первой диаграммы
          var sum_other = {{ sum_other }};
          var sum_job = {{ sum_job }};
          var sum_network = {{ sum_network }};
          var data = [{
            values: [sum_other, sum_job, sum_network],
            labels: ['С подработки', 'С работы', 'С нейросетей'],
            type: 'pie'
          }];
          var layout = {
            title: 'Диаграмма доходов',
            font: {size: 16}
          };
          Plotly.newPlot('chart', data, layout);
  
          // JavaScript код для создания второй диаграммы
          var day_other = {{ day_other }};
          var day_job = {{ day_job }};
          var day_network = {{ day_network }};
          var dataDays = [{
            values: [day_other, day_job, day_network],
            labels: ['C подработки', 'C работы', 'C нейросетей'],
            type: 'pie'
          }];
          var layoutDays = {
            title: 'Диаграмма количества дней',
            font: {size: 16}
          };
          Plotly.newPlot('chart-days', dataDays, layoutDays);
        </script> -->

        <br>
        <h1 class="mb-4" data-aos="fade-up" data-aos-delay="100" style="color: #01070e; text-decoration: underline;">Общая потраченная сумма: {{ expenses_amount }}</h1>
        <section class="site-section">
          <div class="row">
            <div class="col-md-6">
              <img src="{% static 'images/other_dohod.jpg' %}" alt="Image placeholder" class="img-fluid mb-4 w-100">
              <div id="pie-chart"></div>
            </div>
            <div class="col-md-6">         
              {% for i in expenses %}
                <div style="border: 1px solid black; padding: 10px;">
                  <p style="color: #01070e;">Тип расхода: {{ i.type_expenses }}</p>
                  <p style="color: #01070e;">Сумма : {{ i.price }}</p>
                  <p style="color: #01070e;">Дата добавления: {{ i.date }}</p>
                  <p style="color: #01070e;">Комментарий: {{ i.comment }} </p>
                  <p style="color: #01070e;">Вид расходов: {{ i.variety }}</p>
                </div>
              {% endfor %}
            </div>
          </div>
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
          <script>
            var labels = [];
            var values = [];
            {% for i in expenses %}
              labels.push("{{ i.type_expenses }}");
              values.push({{ i.price }});
            {% endfor %};
            var data = [{
              labels: labels,
              values: values,
              type: 'pie'
            }];
            var layout = {
              title: 'Разбивка расходов по типу'
            };
            Plotly.newPlot('pie-chart', data, layout);
          </script>
        </section>
        <section class="site-section">
        </section>
      </div>
    </div>
  </div>
</div>
{% endblock %}

job/templates/main/finance_calculation.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<style>
    .card-header h1 {
  text-align: center;
}
</style>
<style>
    .card-header h2 {
  text-align: center;
}
</style>
<style>
    .col-lg-6 {
      border: 1px solid black;
    }
    .card-header {
      margin-top: 1rem;
    }
</style>

<style>
    .card {
      border: 1px solid black;
    }
    .card-header {
      margin-top: 1rem;
    }
</style>



<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Подсчет ваших расходов
                </div>
                <div class="card-body">
                    <table class="table">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form3 %}
                            {% bootstrap_button button_type="submit" content="Создать" %}
                        </form>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Подсчет средств c основной работы
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% bootstrap_button button_type="submit" content="Создать" %}
                      </form>
                      <br>
                      <form method="post" action="{% url 'job:finance_add_view' %}">
                        {% csrf_token %}
                        
                        {% bootstrap_button button_type="submit" content="Добавить свою работу" %}
                      </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Подсчет средств c нейросетей
                </div>
                <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form1 %}
                    {% bootstrap_button button_type="submit" content="Создать" %}
                  </form>
                  <br>
                  <br>
                  <a href="/job/neuronet/" class="btn btn-primary">Добавить нейросеть</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Подсчет средств c подработки
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form2 %}
                        {% bootstrap_button button_type="submit" content="Создать" %}
                      </form>
                      <br>
                      <form method="post" action="{% url 'job:finance_other_add_view' %}">
                        {% csrf_token %}
                        
                        {% bootstrap_button button_type="submit" content="Добавить свою подработку" %}
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
<script src='{% static "js/jquery-ui.js" %}'></script>
<script src='{% static "js/popper.min.js" %}'></script>
<script src='{% static "js/bootstrap.min.js" %}'></script>
<script src='{% static "js/owl.carousel.min.js" %}'></script>
<script src='{% static "js/jquery.magnific-popup.min.js" %}'></script>
<script src='{% static "js/jquery.sticky.js" %}'></script>
<script src='{% static "js/jquery.waypoints.min.js" %}'></script>
<script src='{% static "js/jquery.animateNumber.min.js" %}'></script>
<script src='{% static "js/aos.js" %}'></script>
<script src='{% static "js/prof.js" %}'></script>
<script src='{% static "js/chit.js" %}'></script>


<script src='{% static "js/main.js" %}'></script>
{% endblock %}